package org.apache.nifi.web.jsp.WEB_002dINF.partials.provenance;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class provenance_002devent_002ddetails_002ddialog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n\n<div id=\"event-details-dialog\">\n    <div id=\"event-details-dialog-content\">\n        <div id=\"event-details-tabs\"></div>\n        <div id=\"event-details-tabs-content\">\n            <div id=\"event-details-tab-content\" class=\"details-tab\">\n                <span id=\"provenance-event-id\" class=\"hidden\"></span>\n                <span id=\"provenance-event-cluster-node-id\" class=\"hidden\"></span>\n                <div class=\"settings-left\">\n                    <div id=\"event-details\">\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">Time</div>\n                            <div id=\"provenance-event-time\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">Event Duration</div>\n                            <div id=\"provenance-event-duration\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n");
      out.write("                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">Lineage Duration</div>\n                            <div id=\"provenance-lineage-duration\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">Type</div>\n                            <div id=\"provenance-event-type\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">FlowFile Uuid</div>\n                            <div id=\"provenance-event-flowfile-uuid\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">File Size</div>\n");
      out.write("                            <div id=\"provenance-event-file-size\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">Component Id</div>\n                            <div id=\"provenance-event-component-id\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">Component Name</div>\n                            <div id=\"provenance-event-component-name\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">Component Type</div>\n                            <div id=\"provenance-event-component-type\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n");
      out.write("                        </div>\n                        <div id=\"additional-provenance-details\"></div>\n                        <div class=\"event-detail\">\n                            <div class=\"detail-name\">Details</div>\n                            <div id=\"provenance-event-details\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                    </div>\n                </div>\n                <div class=\"spacer\">&nbsp;</div>\n                <div class=\"settings-right\">\n                    <div id=\"parent-flowfiles\">\n                        <div class=\"event-header\">Parent FlowFiles (<span id=\"parent-flowfile-count\"></span>)</div>\n                        <div id=\"parent-flowfiles-container\" class=\"flowfile-container\"></div>\n                    </div>\n                    <div id=\"child-flowfiles\">\n                        <div class=\"event-header\">Child FlowFiles (<span id=\"child-flowfile-count\"></span>)</div>\n                        <div id=\"child-flowfiles-container\"class=\"flowfile-container\"></div>\n");
      out.write("                    </div>\n                </div>\n                <div class=\"clear\"></div>\n            </div>\n            <div id=\"attributes-tab-content\" class=\"details-tab\">\n                <div id=\"attributes-details\">\n                    <div id=\"attributes-header\" class=\"event-header\">Attribute Values</div>\n                    <div id=\"modified-attribute-toggle-container\">\n                        <div id=\"modified-attribute-toggle-label\">Only show modified</div>\n                        <div id=\"modified-attribute-toggle\" class=\"nf-checkbox checkbox-unchecked\"></div>\n                        <div class=\"clear\"></div>\n                    </div>\n                    <div class=\"clear\"></div>\n                    <div id=\"attributes-container\"></div>\n                </div>\n            </div>\n            <div id=\"content-tab-content\" class=\"details-tab\">\n                <div class=\"settings-left\">\n                    <div id=\"input-content-details\" class=\"content-details\">\n                        <div id=\"input-content-header\" class=\"event-header\">Input Claim</div>\n");
      out.write("                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Container</div>\n                            <div id=\"input-content-container\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Section</div>\n                            <div id=\"input-content-section\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Identifier</div>\n                            <div id=\"input-content-identifier\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Offset</div>\n");
      out.write("                            <div id=\"input-content-offset\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Size</div>\n                            <div id=\"input-content-size\" class=\"content-detail-value\"></div>\n                            <div id=\"input-content-bytes\" class=\"content-detail-value hidden\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div id=\"input-content-download\" class=\"button hidden\">Download</div>\n                            <div id=\"input-content-view\" class=\"button hidden\">View</div>\n                            <div class=\"clear\"></div>\n                        </div>\n                    </div>\n                </div>\n                <div class=\"spacer\">&nbsp;</div>\n                <div class=\"settings-right\">\n");
      out.write("                    <div id=\"output-content-details\" class=\"content-details\">\n                        <div class=\"event-header\">Output Claim</div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Container</div>\n                            <div id=\"output-content-container\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Section</div>\n                            <div id=\"output-content-section\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Identifier</div>\n                            <div id=\"output-content-identifier\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n");
      out.write("                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Offset</div>\n                            <div id=\"output-content-offset\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div class=\"content-detail-name\">Size</div>\n                            <div id=\"output-content-size\" class=\"content-detail-value\"></div>\n                            <div id=\"output-content-bytes\" class=\"content-detail-value hidden\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"event-detail\">\n                            <div id=\"output-content-download\" class=\"button hidden\">Download</div>\n                            <div id=\"output-content-view\" class=\"button hidden\">View</div>\n                            <div class=\"clear\"></div>\n");
      out.write("                        </div>\n                    </div>\n                </div>\n                <div class=\"clear\"></div>\n                <div id=\"replay-details\" class=\"content-details hidden\">\n                    <div class=\"event-header\">Replay</div>\n                    <div id=\"replay-content-connection\" class=\"event-detail\">\n                        <div class=\"content-detail-name\">Connection Id</div>\n                        <div id=\"replay-connection-id\" class=\"content-detail-value\"></div>\n                        <div class=\"clear\"></div>\n                    </div>\n                    <div id=\"replay-content-message\" class=\"hidden\"></div>\n                    <div class=\"event-detail\">\n                        <div id=\"replay-content\" class=\"button\">Submit</div>\n                        <div class=\"clear\"></div>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
