package org.apache.nifi.web.jsp.WEB_002dINF.partials.canvas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class processor_002dconfiguration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n\n<div id=\"processor-configuration\">\n    <div class=\"processor-configuration-tab-container\">\n        <div id=\"processor-configuration-tabs\"></div>\n        <div id=\"processor-configuration-tabs-content\">\n            <div id=\"processor-standard-settings-tab-content\" class=\"configuration-tab\">\n                <div class=\"settings-left\">\n                    <div class=\"setting\">\n                        <div class=\"setting-name\">Name</div>\n                        <div class=\"setting-field\">\n                            <input type=\"text\" id=\"processor-name\" name=\"processor-name\"/>\n                            <div class=\"processor-enabled-container\">\n                                <div id=\"processor-enabled\" class=\"nf-checkbox checkbox-unchecked\"></div>\n                                <span> Enabled</span>\n                            </div>\n                        </div>\n                    </div>\n                    <div class=\"setting\">\n                        <div class=\"setting-name\">Id</div>\n                        <div class=\"setting-field\">\n");
      out.write("                            <span id=\"processor-id\"></span>\n                        </div>\n                    </div>\n                    <div class=\"setting\">\n                        <div class=\"setting-name\">Type</div>\n                        <div class=\"setting-field\">\n                            <span id=\"processor-type\"></span>\n                        </div>\n                    </div>\n                    <div class=\"setting\">\n                        <div class=\"penalty-duration-setting\">\n                            <div class=\"setting-name\">\n                                Penalty duration\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"The amount of time used when this processor penalizes a FlowFile.\"/>\n                            </div>\n                            <div class=\"setting-field\">\n                                <input type=\"text\" id=\"penalty-duration\" name=\"penalty-duration\" class=\"small-setting-input\"/>\n                            </div>\n");
      out.write("                        </div>\n                        <div class=\"yield-duration-setting\">\n                            <div class=\"setting-name\">\n                                Yield duration\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"When a processor yields, it will not be scheduled again until this amount of time elapses.\"/>\n                            </div>\n                            <div class=\"setting-field\">\n                                <input type=\"text\" id=\"yield-duration\" name=\"yield-duration\" class=\"small-setting-input\"/>\n                            </div>\n                        </div>\n                        <div class=\"clear\"></div>\n                    </div>\n                    <div class=\"setting\">\n                        <div class=\"bulletin-setting\">\n                            <div class=\"setting-name\">\n                                Bulletin level\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"The level at which this processor will generate bulletins.\"/>\n");
      out.write("                            </div>\n                            <div class=\"setting-field\">\n                                <div id=\"bulletin-level-combo\"></div>\n                            </div>\n                        </div>\n                        <div class=\"clear\"></div>\n                    </div>\n                </div>\n                <div class=\"spacer\">&nbsp;</div>\n                <div class=\"settings-right\">\n                    <div class=\"setting\">\n                        <div class=\"setting-name\">\n                            Auto terminate relationships\n                            <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"Will automatically terminate FlowFiles sent to a given relationship if it is not defined elsewhere.\"/>\n                        </div>\n                        <div class=\"setting-field\">\n                            <div id=\"auto-terminate-relationship-names\"></div>\n                        </div>\n                    </div>\n                </div>\n");
      out.write("            </div>\n            <div id=\"processor-scheduling-tab-content\" class=\"configuration-tab\">\n                <div class=\"settings-left\">\n                    <div class=\"setting\">\n                        <div class=\"scheduling-strategy-setting\">\n                            <div class=\"setting-name\">\n                                Scheduling strategy\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"The strategy used to schedule this processor.\"/>\n                            </div>\n                            <div class=\"setting-field\">\n                                <div type=\"text\" id=\"scheduling-strategy-combo\"></div>\n                            </div>\n                        </div>\n                        <div id=\"event-driven-warning\" class=\"hidden\">\n                            <div class=\"processor-configuration-warning-icon\"></div>\n                            This strategy is experimental\n                        </div>\n                        <div class=\"clear\"></div>\n");
      out.write("                    </div>\n                    <div id=\"timer-driven-options\" class=\"setting\">\n                        <div class=\"concurrently-schedulable-tasks-setting\">\n                            <div class=\"setting-name\">\n                                Concurrent tasks\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"The number of tasks that should be concurrently scheduled for this processor.\"/>\n                            </div>\n                            <div class=\"setting-field\">\n                                <input type=\"text\" id=\"timer-driven-concurrently-schedulable-tasks\" name=\"timer-driven-concurrently-schedulable-tasks\" class=\"small-setting-input\"/>\n                            </div>\n                        </div>\n                        <div class=\"scheduling-period-setting\">\n                            <div class=\"setting-name\">\n                                Run schedule\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"The amount of time that should elapse between task executions.\"/>\n");
      out.write("                            </div>\n                            <div class=\"setting-field\">\n                                <input type=\"text\" id=\"timer-driven-scheduling-period\" name=\"timer-driven-scheduling-period\" class=\"small-setting-input\"/>\n                            </div>\n                        </div>\n                        <div class=\"clear\"></div>\n                    </div>\n                    <div id=\"event-driven-options\" class=\"setting\">\n                        <div class=\"concurrently-schedulable-tasks-setting\">\n                            <div class=\"setting-name\">\n                                Concurrent tasks\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"The number of tasks that should be concurrently scheduled for this processor.\"/>\n                            </div>\n                            <div class=\"setting-field\">\n                                <input type=\"text\" id=\"event-driven-concurrently-schedulable-tasks\" name=\"event-driven-concurrently-schedulable-tasks\" class=\"small-setting-input\"/>\n");
      out.write("                            </div>\n                        </div>\n                        <div class=\"clear\"></div>\n                    </div>\n                    <div id=\"cron-driven-options\" class=\"setting\">\n                        <div class=\"concurrently-schedulable-tasks-setting\">\n                            <div class=\"setting-name\">\n                                Concurrent tasks\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"The number of tasks that should be concurrently scheduled for this processor.\"/>\n                            </div>\n                            <div class=\"setting-field\">\n                                <input type=\"text\" id=\"cron-driven-concurrently-schedulable-tasks\" name=\"cron-driven-concurrently-schedulable-tasks\" class=\"small-setting-input\"/>\n                            </div>\n                        </div>\n                        <div class=\"scheduling-period-setting\">\n                            <div class=\"setting-name\">\n");
      out.write("                                Run schedule\n                                <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\" title=\"The CRON expression that defines when this processor should run.\"/>\n                            </div>\n                            <div class=\"setting-field\">\n                                <input type=\"text\" id=\"cron-driven-scheduling-period\" name=\"cron-driven-scheduling-period\" class=\"small-setting-input\"/>\n                            </div>\n                        </div>\n                        <div class=\"clear\"></div>\n                    </div>\n                </div>\n                <div class=\"spacer\">&nbsp;</div>\n                <div id=\"run-duration-setting-container\" class=\"settings-right\">\n                    <div class=\"setting\">\n                        <div class=\"setting-name\">\n                            Run duration\n                            <img class=\"setting-icon icon-info\" src=\"images/iconInfo.png\" alt=\"Info\"\n                                 title=\"When scheduled to run, the processor will continue running for up to this duration. A run duration of 0ms will execute once when scheduled.\"/>\n");
      out.write("                        </div>\n                        <div class=\"setting-field\" style=\"overflow: visible;\">\n                            <div id=\"run-duration-container\">\n                                <div id=\"run-duration-labels\">\n                                    <div id=\"run-duration-zero\">0ms</div>\n                                    <div id=\"run-duration-one\">25ms</div>\n                                    <div id=\"run-duration-two\">50ms</div>\n                                    <div id=\"run-duration-three\">100ms</div>\n                                    <div id=\"run-duration-four\">250ms</div>\n                                    <div id=\"run-duration-five\">500ms</div>\n                                    <div id=\"run-duration-six\">1s</div>\n                                    <div id=\"run-duration-seven\">2s</div>\n                                    <div class=\"clear\"></div>\n                                </div>\n                                <div id=\"run-duration-slider\"></div>\n                                <div id=\"run-duration-explanation\">\n");
      out.write("                                    <div id=\"min-run-duration-explanation\">Lower latency</div>\n                                    <div id=\"max-run-duration-explanation\">Higher throughput</div>\n                                    <div class=\"clear\"></div>\n                                </div>\n                                <div id=\"run-duration-data-loss\" class=\"hidden\">\n                                    <div class=\"processor-configuration-warning-icon\"></div>\n                                    Source Processors with a run duration greater than 0ms and no incoming connections could lose data when NiFi is shutdown.\n                                </div>\n                            </div>\n                        </div>\n                    </div>\n                </div>\n            </div>\n            <div id=\"processor-properties-tab-content\" class=\"configuration-tab\">\n                <div id=\"processor-properties\"></div>\n            </div>\n            <div id=\"processor-comments-tab-content\" class=\"configuration-tab\">\n");
      out.write("                <textarea cols=\"30\" rows=\"4\" id=\"processor-comments\" name=\"processor-comments\" class=\"setting-input\"></textarea>\n            </div>\n        </div>\n    </div>\n</div>\n<div id=\"new-processor-property-container\"></div>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
